language: node_js
node_js:
  - 10

notifications:
  webhooks: https://www.travisbuddy.com/?insertMode=update&only=failed,errored
  email: false

cache:
  directories:
    - node_modules

install:
  - npm ci

stages:
  - name: test
  - name: build

jobs:
  include:
    - stage: test
      name: 'Lint and test'
      script:
        - npm run lint
        - npm run test:unit

    - stage: build
      script:
        - npm run build